#!/bin/bash

read -p "This will add $USER to group imu are you sure? y/n: " -n 1 -r
echo #newline
if [[ $REPLY =~ ^[Yy]$ ]]
then
	# add group and user
	sudo groupadd imu
	sudo adduser $USER imu

	# addudev rule
	DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )" # get directory where this script is stored
	sudo cp $DIR/imu_3dm_gx4.rules /etc/udev/rules.d/

	#reload udev
	sudo udevadm control --reload-rules
fi
